# Generated by Django 2.2.14 on 2021-10-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211022_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
